apiVersion: v1
kind: Service
metadata:
  name: fgc-catalog-api
  labels:
    app: fgc-catalog-api
spec:
  type: ClusterIP
  selector:
    app: fgc-catalog-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
