<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fgc.Catalog.Application\Fgc.Catalog.Application.csproj" />
    <ProjectReference Include="..\Fgc.Catalog.Domain\Fgc.Catalog.Domain.csproj" />
  </ItemGroup>

</Project>
